# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/gui/lynktree.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LynktreeGUI(object):
    def setupUi(self, LynktreeGUI):
        LynktreeGUI.setObjectName("LynktreeGUI")
        LynktreeGUI.resize(800, 600)
        self.lcdFFMC = QtWidgets.QLCDNumber(LynktreeGUI)
        self.lcdFFMC.setGeometry(QtCore.QRect(670, 10, 111, 41))
        self.lcdFFMC.setObjectName("lcdFFMC")
        self.lcdDMC = QtWidgets.QLCDNumber(LynktreeGUI)
        self.lcdDMC.setGeometry(QtCore.QRect(670, 70, 111, 41))
        self.lcdDMC.setObjectName("lcdDMC")
        self.lcdDC = QtWidgets.QLCDNumber(LynktreeGUI)
        self.lcdDC.setGeometry(QtCore.QRect(670, 130, 111, 41))
        self.lcdDC.setObjectName("lcdDC")
        self.lcdISI = QtWidgets.QLCDNumber(LynktreeGUI)
        self.lcdISI.setGeometry(QtCore.QRect(670, 190, 111, 41))
        self.lcdISI.setObjectName("lcdISI")
        self.lcdBUI = QtWidgets.QLCDNumber(LynktreeGUI)
        self.lcdBUI.setGeometry(QtCore.QRect(670, 260, 111, 41))
        self.lcdBUI.setObjectName("lcdBUI")

        self.retranslateUi(LynktreeGUI)
        QtCore.QMetaObject.connectSlotsByName(LynktreeGUI)

    def retranslateUi(self, LynktreeGUI):
        _translate = QtCore.QCoreApplication.translate
        LynktreeGUI.setWindowTitle(_translate("LynktreeGUI", "Lynktree"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LynktreeGUI = QtWidgets.QDialog()
    ui = Ui_LynktreeGUI()
    ui.setupUi(LynktreeGUI)
    LynktreeGUI.show()
    sys.exit(app.exec_())
