# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/gui/lynktree.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LynktreeGUI(object):
    def setupUi(self, LynktreeGUI):
        LynktreeGUI.setObjectName("LynktreeGUI")
        LynktreeGUI.resize(800, 600)
        self.verticalLayoutWidget = QtWidgets.QWidget(LynktreeGUI)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 771, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lyMaps = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lyMaps.setContentsMargins(0, 0, 0, 0)
        self.lyMaps.setObjectName("lyMaps")
        self.widget = QtWidgets.QWidget(LynktreeGUI)
        self.widget.setGeometry(QtCore.QRect(670, 10, 111, 271))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdFFMC = QtWidgets.QLCDNumber(self.widget)
        self.lcdFFMC.setAutoFillBackground(False)
        self.lcdFFMC.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lcdFFMC.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdFFMC.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdFFMC.setObjectName("lcdFFMC")
        self.verticalLayout.addWidget(self.lcdFFMC)
        self.lcdDMC = QtWidgets.QLCDNumber(self.widget)
        self.lcdDMC.setAutoFillBackground(False)
        self.lcdDMC.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lcdDMC.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdDMC.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdDMC.setObjectName("lcdDMC")
        self.verticalLayout.addWidget(self.lcdDMC)
        self.lcdDC = QtWidgets.QLCDNumber(self.widget)
        self.lcdDC.setAutoFillBackground(False)
        self.lcdDC.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lcdDC.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdDC.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdDC.setObjectName("lcdDC")
        self.verticalLayout.addWidget(self.lcdDC)
        self.lcdISI = QtWidgets.QLCDNumber(self.widget)
        self.lcdISI.setAutoFillBackground(False)
        self.lcdISI.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lcdISI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdISI.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdISI.setObjectName("lcdISI")
        self.verticalLayout.addWidget(self.lcdISI)
        self.lcdBUI = QtWidgets.QLCDNumber(self.widget)
        self.lcdBUI.setAutoFillBackground(False)
        self.lcdBUI.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lcdBUI.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdBUI.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdBUI.setObjectName("lcdBUI")
        self.verticalLayout.addWidget(self.lcdBUI)

        self.retranslateUi(LynktreeGUI)
        QtCore.QMetaObject.connectSlotsByName(LynktreeGUI)

    def retranslateUi(self, LynktreeGUI):
        _translate = QtCore.QCoreApplication.translate
        LynktreeGUI.setWindowTitle(_translate("LynktreeGUI", "Lynktree"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LynktreeGUI = QtWidgets.QDialog()
    ui = Ui_LynktreeGUI()
    ui.setupUi(LynktreeGUI)
    LynktreeGUI.show()
    sys.exit(app.exec_())
